Algoritmo "Entrada e Saída de Dados"

// Descrição   : Entrada e Saída de Dados
// Autor(a)    : Marcos Emanuel
// Data atual  : 20/10/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite a sua nota:")
   leia(nota)
   
   escreval("O nome digitado foi: ", nome)
   escreval("A nota digitada foi:", nota)

Fimalgoritmo